---
- hosts: localhost
  connection: local

  vars_files:
    - vars/vault.yml
    - vars/globals.yml
    - vars/os_paths.yml


  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - 'vars/packages/vars_{{ansible_distribution}}{{ansible_distribution_major_version}}.yml'
    - include_vars: 'vars/vault.yml'
    - include_vars: 
        file: 'vars/local_keys.yml'
        hash_behaviour: merge
    - name: Switch app trunk
      set_fact:
        app_trunk: '~/{{app_details["name"]}}'
    - name: Install rsync
      become: true
      package:
        name: rsync
    - name: Create app directory
      file:
        path: '{{test_trunk}}'
        state: directory

  vars:
    app_trunk: '{{domain["app_root"]|default("~")}}/{{app_details["name"]}}'
    test_trunk: '../test_trash/{{app_details["name"]}}'
    ansible_user: '{{lookup("env", "USER")}}'

  roles:
    - repo-check
    - role: mysql-setup
      setup_pass: '{{keys["db_pass_setup"]}}'
      socket_path: '{{dev_files["mysql_socket"]}}'
      sql_scripts_src: ../sql_scripts
      env_name: '{{app_details["prefix"]|lower}}_env'
      engine_src: '{{src_dirs["engine"]}}/'
    - role: tests-setup

  tasks:
    
    - name: Run unit tests
      command:
        chdir: ../src/tests
        argv:
          - '../{{test_trunk}}/{{app_details["prefix"]|lower}}_env/bin/python'
          - -m
          - pytest
          - -s
      environment:
        DSF_DB_PASS_SETUP: '{{keys["db_pass_setup"]}}'
        DSF_DB_PASS_OWNER: '{{keys["db_pass_owner"]}}'
        DSF_DB_PASS_API: '{{keys["db_pass_api"]}}'
        DSF_DB_PASS_RADIO: '{{keys["db_pass_radio"]}}'
        DSF_DB_PASS_JANITOR: '{{keys["db_pass_janitor"]}}'
        DSF_DATABASE_NAME: '{{app_details["db"]}}'
        DSF_SQL_SCRIPTS_DEST: '../{{test_trunk}}/sql_scripts'
        DSF_APP_ROOT: '{{test_trunk}}'
        DSF_TEMPLATES_DEST: '../{{test_trunk}}/files'
        DSF_ICES_CONFIGS_DIR: '../{{test_trunk}}/ices_configs'
        DSF_AUTH_SECRET_KEY: '{{keys["auth_secret_key"]}}'
        DSF_BACK_KEY: '{keys["back_key"]}'
        DSF_CONTENT_DIR: '../{{test_trunk}}/content'
        DSF_PY_MODULE_DIR: '../{{test_trunk}}/ices_modules'
        DSF_LIVE_CONFIG_PATH: '../{{test_trunk}}/app_conf.json'
        DSF_EVENT_LOGS_DIR: '../{{test_trunk}}/event_logs'
        DSF_QUEUE_FILES_DIR: '../{{test_trunk}}/queues'
      when: skip_tests|default(false)|bool != true
    
    