---
- hosts: all

  vars_files:
    - vars/vault.yml
    - vars/globals.yml

  tasks:
    - name: Copy configs and scripts for server maintenance
      include_role:
        name: maintenance-helper-setup
      vars:
        mt_user: '{{domain["server_user"]}}'
