---
- hosts: all


  vars:
    app_trunk: '{{domain["app_root"]|default("~")}}/{{app_details["name"]}}'
    test_trunk: '../test_trash/{{app_details["name"]}}'
    ansible_common_remote_group: '{{domain["group"]}}'


  vars_files:
    - vars/vault.yml
    - vars/globals.yml
    - vars/os_paths.yml
  
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - 'vars/packages/vars_{{ansible_distribution}}{{ansible_distribution_major_version}}.yml'
    - include_vars: 
        file: 'vars/vault.yml'
        hash_behaviour: merge
    - include_vars: 
        file: 'vars/local_keys.yml'
        hash_behaviour: merge
      when: inventory_hostname in ["127.0.0.1", "localhost"]

  tasks:
    - name: Add user
      user:
        name: '{{domain["server_user"]}}'
        group: '{{domain["group"]}}'
        shell: /bin/bash
      become: true
    - name: Allow login user to su as server user
      blockinfile:
        path: /etc/pam.d/su
        insertafter: '^auth +sufficient pam_rootok.so'
        marker: '# {mark} ANSIBLE - {{domain["server_user"]}}'
        block: |
          auth  [success=ignore default=1] pam_succeed_if.so user = {{domain["server_user"]}}
          auth  sufficient                 pam_succeed_if.so use_uid user = {{domain["user"]}}
      become: true
    - name: Enable Linger for server user user
      command: 
        argv:
          - loginctl 
          - enable-linger 
          - '{{domain["server_user"]}}'
        creates: '/var/lib/systemd/linger/{{domain["server_user"]}}'
      become: true
