---
- hosts: all

  vars:
    app_trunk: '{{domain["app_root"]}}/{{app_details["name"]}}'
    test_trunk: '../test_trash/{{app_details["name"]}}'
    ansible_common_remote_group: '{{domain["group"]}}'

  vars_files:
    - vars/vault.yml
    - vars/globals.yml
    - vars/os_paths.yml

  handlers:
    - name: Restart icecast
      become: true
      service:
        name: '{{packages["icecast"]}}'
        enabled: true
        state: restarted
    - name: Reload groups
      become: true
      reboot:
      when: ansible_host not in ["127.0.0.1", "localhost"] 

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - 'vars/packages/vars_{{ansible_distribution}}{{ansible_distribution_major_version}}.yml'
    - name: Set local host app app_trunk
      set_fact:
        app_trunk: '{{"~"|expanduser}}/{{app_details["name"]}}'
        domain: '{{domain|combine(my_overrides, recursive=True)}}'
      vars:
        my_overrides:
          app_root: '{{"~"|expanduser}}'
      when: inventory_hostname in ["127.0.0.1", "localhost"]
    - name: Update apt cache if needed
      apt: update_cache=true cache_valid_time=3600
      become: true
      when: ansible_os_family == "Debian"

  tasks:
    - name: Create ices directories
      file:
        path: '{{item}}'
        state: directory
        owner: '{{domain["server_user"]}}'
        group: '{{domain["group"]}}'
        mode: 'g+w'
      no_log: true
      become: true
      loop:
        - '{{app_trunk}}/ices_configs'
        - '{{domain["app_root"]}}/.local'
        - '{{domain["app_root"]}}/.local/share'
    - name: install icecast
      package: 
        name: '{{packages["icecast"]}}'
      become: true
      notify: Restart icecast
    - name: Grant read to icecast config
      user:
        name: '{{domain["server_user"]}}'
        groups: icecast
        append: true
      become: true
      notify: Reload groups
    - name: Python setup.
      include_role:
        name: python-setup
      vars:
        env_name: '{{app_details["prefix"]|lower}}_env'
        engine_src: '{{src_dirs["engine"]}}/'
        working_dir: '{{app_trunk}}'
        app_group: '{{domain["group"]}}'
    - name: Extract python version string.
      command: 
        argv:
          - '{{app_trunk}}/{{app_details["prefix"]|lower}}_env/bin/python'
          - -V
      check_mode: false
      register: python_version
    - name: Extract python minor version and env path
      set_fact:
        py_minor_version: '{{python_version.stdout.split(" ")[1].split(".")[1]}}'
    - name: Install ices
      include_role:
        name: ices-install
      vars:
        ices_dependencies: '{{packages["ices_dependencies"]}}'
        build_path: /tmp/build/ices
        install_path: '{{domain["app_root"]}}/.local'
        python_path: '{{app_trunk}}/{{app_details["prefix"]|lower}}_env/bin/python'
        python_module_dir: '{{app_trunk}}/ices_modules'
        prefix: '{{app_details["prefix"]|lower}}-'
        target_version: '0.6.2'
    - name: Copy the python station modules
      copy:
        src: radio_handle.py 
        dest: '{{app_trunk}}/ices_modules/station.py'
    - name: Generate source password
      command: openssl rand -hex 16
      register: source_password
    - name: Generate relay password
      command: openssl rand -hex 16
      register: relay_password
    - name: Generate admin password
      command: openssl rand -hex 16
      register: admin_password
    - name: Shutdown all stations
      command:
        argv:
          - '{{app_trunk}}/{{app_details["prefix"]|lower}}_env/bin/python'
          - -m
          - '{{app_details["engine"]}}.one_offs.shutdown_stations'
      environment:
        DSF_DB_PASS_JANITOR: '{{keys["db_pass_janitor"]}}'
        DSF_DATABASE_NAME: '{{app_details["db"]}}'
    - name: Update icecast config
      lineinfile:
        dest: '{{dev_files["icecast_config"]}}'
        regexp: '{{item.regexp}}'
        line: '{{item.line}}'
        state: present
      become: true
      loop:
        - regexp: '<source-password>\w*</source-password>'
          line: '<source-password>{{source_password.stdout}}</source-password>'
        - regexp: '<relay-password>\w*</relay-password>'
          line: '<relay-password>{{relay_password.stdout}}</relay-password>'
        - regexp: '<admin-password>\w*</admin-password>'
          line: '<admin-password>{{admin_password.stdout}}</admin-password>'
      no_log: true
      notify: Restart icecast
    - name: Update the ices configs
      lineinfile:
        dest: '{{item}}'
        regexp: '<Password>\w*</Password>'
        line: '<Password>{{source_password.stdout}}</Password>'
        state: present
      with_fileglob: '{{app_trunk}}/ices_configs/*.conf'
      no_log: true
    