---
- hosts: localhost
  connection: local

  vars_files:
    - vars/globals.yml
    - vars/os_paths.yml


  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - 'vars/packages/vars_{{ansible_distribution}}{{ansible_distribution_major_version}}.yml'
    - include_vars: 
        file: 'vars/local_keys.yml'
        hash_behaviour: merge
    - name: Create app directory
      file:
        path: '{{test_trunk}}'
        state: directory

  vars:
    app_trunk: '{{domain["app_root"]|default("~")}}/{{app_details["name"]}}'
    test_trunk: '../test_trash/{{app_details["name"]}}'
    ansible_user: '{{lookup("env", "USER")}}'

  roles:
    - role: tests-setup
  
  tasks:
    - name: Setup App Specific Db stuff.
      command:
        argv:
          - '{{app_trunk}}/{{app_details["prefix"]|lower}}_env/bin/alembic'
          - upgrade
          - head
      register: migrate_results
      environment:
        DSF_DB_FILE: '{{lookup("env", "MCR_DB_FILE")}}'