---
- hosts: all

  vars_files:
    - vars/vault.yml
    - vars/globals.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - 'vars/packages/vars_{{ansible_distribution}}{{ansible_distribution_major_version}}.yml'

  tasks:
    - name: Copy configs and scripts for server maintenance
      include_role:
        name: maintenance-helper-setup
      vars:
        mt_user: '{{domain["user"]}}'
    - name: Setup fail2ban
      include_role:
        name: fail2ban-setup
