---
- hosts: webserver

  vars_files:
    - ../vars/vault.yml
    - ../vars/globals.yml

  tasks:
    - name: Install PyMySQL
      become: true
      apt:
        name: '{{packages["pymysql"]}}'
        state: present
    - name: Dump MySQL database
      community.mysql.mysql_db:
        login_user: '{{ app_details["db_owner"] }}'
        login_password: '{{ keys["db_pass_owner"] }}'
        name: '{{ app_details["db"] }}'
        state: dump
        target: /tmp/backup.sql
        dump_extra_args: "{{ dump_args|default('') }}"
    - name: Fetched the dumped sql
      fetch:
        src: /tmp/backup.sql
        dest: ~/Documents/mysql_dumps/{{ now(fmt='%Y%m%d_%H%M')}}_backup.sql
        flat: true
    - name: Clean up the dumped sql
      file:
        path: /tmp/backup.sql
        state: absent


