
"""
This type stub file was generated by pyright.
"""

from tinytag.tinytag import Flac as Flac, \
    ID3 as ID3, \
    Ogg as Ogg, \
    TinyTag as TinyTag, \
    TinyTagException as TinyTagException, \
    Wave as Wave


__version__: str = ...
if __name__ == '__main__':
    ...
