"""add flatnames

Revision ID: 1906ab109e0e
Revises: 
Create Date: 2026-02-01 13:25:27.638163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from musical_chairs_libs.tables import artists, albums, users



# revision identifiers, used by Alembic.
revision: str = '1906ab109e0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('flatname', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('flatname', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('flatusername', sa.Text(), nullable=True))

    op.execute(
        sa.update(artists).values(
            flatname = sa.func.format_name_for_search(
                artists.c.name
            )
        )
    )
    op.execute(
        sa.update(albums).values(
            flatname = sa.func.format_name_for_search(
                albums.c.name
            )
        )
    )
    op.execute(
        sa.update(users).values(
            flatusername = sa.func.format_name_for_search(
                users.c.username
            )
        )
    )
    with op.batch_alter_table("artists") as batch_op:
        batch_op.alter_column('flatname',nullable=False)
    with op.batch_alter_table("albums") as batch_op:
        batch_op.alter_column('flatname',nullable=False)
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column('flatusername',nullable=False)
    
    with op.batch_alter_table('playlists') as batch_op:
        batch_op.alter_column('description',new_column_name='displayname')
        
    op.create_index('idx_uniqueflatusername', 'users', ['flatusername'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_uniqueflatusername', table_name='users')
    op.drop_column('users', 'flatusername')
    op.add_column('playlists', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('playlists', 'displayname')
    op.drop_column('artists', 'flatname')
    op.drop_column('albums', 'flatname')
    # ### end Alembic commands ###
