"""shrink-treepath

Revision ID: 3dd794dbd141
Revises: 7d6c075f5607
Create Date: 2026-02-15 14:16:30.916964

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import musical_chairs_libs.tables as tbl


# revision identifiers, used by Alembic.
revision: str = '3dd794dbd141'
down_revision: str | Sequence[str] | None = '7d6c075f5607'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index("idx_uniquesongpath",tbl.songs.name, if_exists=True)
    op.alter_column(
        tbl.songs.name,
        tbl.sg_path.name,
        type_=sa.String(500),
        nullable=False
    )
    op.create_index(
        "idx_uniquesongpath",
        tbl.songs.name,
        [tbl.sg_path],
        unique=True,
        if_not_exists=True
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###