"""ondelete-rules

Revision ID: f993048349d3
Revises: 3dd794dbd141
Create Date: 2026-02-20 13:52:02.165189

"""
from typing import Sequence

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'f993048349d3'
down_revision: str | Sequence[str] | None = '3dd794dbd141'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lastplayed_ibfk_2'), 'lastplayed', type_='foreignkey')
    op.drop_constraint(op.f('lastplayed_ibfk_1'), 'lastplayed', type_='foreignkey')
    op.create_foreign_key(None, 'lastplayed', 'stations', ['stationfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lastplayed', 'songs', ['songfk'], ['pk'], ondelete='CASCADE')

    op.drop_constraint(op.f('playlistssongs_ibfk_3'), 'playlistssongs', type_='foreignkey')
    op.drop_constraint(op.f('playlistssongs_ibfk_2'), 'playlistssongs', type_='foreignkey')
    op.drop_constraint(op.f('playlistssongs_ibfk_1'), 'playlistssongs', type_='foreignkey')
    op.create_foreign_key(None, 'playlistssongs', 'users', ['lastmodifiedbyuserfk'], ['pk'], ondelete='SET NULL')
    op.create_foreign_key(None, 'playlistssongs', 'playlists', ['playlistfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'playlistssongs', 'songs', ['songfk'], ['pk'], ondelete='CASCADE')

    op.drop_constraint(op.f('stationlogs_ibfk_3'), 'stationlogs', type_='foreignkey')
    op.drop_constraint(op.f('stationlogs_ibfk_1'), 'stationlogs', type_='foreignkey')
    op.drop_constraint(op.f('stationlogs_ibfk_2'), 'stationlogs', type_='foreignkey')
    op.create_foreign_key(None, 'stationlogs', 'songs', ['songfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stationlogs', 'stations', ['stationfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stationlogs', 'users', ['userfk'], ['pk'], ondelete='SET NULL')

    op.drop_constraint(op.f('stationsalbums_ibfk_2'), 'stationsalbums', type_='foreignkey')
    op.drop_constraint(op.f('stationsalbums_ibfk_1'), 'stationsalbums', type_='foreignkey')
    op.drop_constraint(op.f('stationsalbums_ibfk_3'), 'stationsalbums', type_='foreignkey')
    op.create_foreign_key(None, 'stationsalbums', 'stations', ['stationfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stationsalbums', 'albums', ['albumfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stationsalbums', 'users', ['lastmodifiedbyuserfk'], ['pk'], ondelete='SET NULL')

    op.drop_constraint(op.f('stationsplaylists_ibfk_2'), 'stationsplaylists', type_='foreignkey')
    op.drop_constraint(op.f('stationsplaylists_ibfk_1'), 'stationsplaylists', type_='foreignkey')
    op.drop_constraint(op.f('stationsplaylists_ibfk_3'), 'stationsplaylists', type_='foreignkey')
    op.create_foreign_key(None, 'stationsplaylists', 'stations', ['stationfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stationsplaylists', 'playlists', ['playlistfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stationsplaylists', 'users', ['lastmodifiedbyuserfk'], ['pk'], ondelete='SET NULL')

    op.drop_constraint(op.f('stationssongs_ibfk_1'), 'stationssongs', type_='foreignkey')
    op.drop_constraint(op.f('stationssongs_ibfk_2'), 'stationssongs', type_='foreignkey')
    op.drop_constraint(op.f('stationssongs_ibfk_3'), 'stationssongs', type_='foreignkey')
    op.create_foreign_key(None, 'stationssongs', 'stations', ['stationfk'], ['pk'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stationssongs', 'users', ['lastmodifiedbyuserfk'], ['pk'], ondelete='SET NULL')
    op.create_foreign_key(None, 'stationssongs', 'songs', ['songfk'], ['pk'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'stationssongs', type_='foreignkey')
    # op.drop_constraint(None, 'stationssongs', type_='foreignkey')
    # op.drop_constraint(None, 'stationssongs', type_='foreignkey')
    # op.create_foreign_key(op.f('stationssongs_ibfk_3'), 'stationssongs', 'users', ['lastmodifiedbyuserfk'], ['pk'])
    # op.create_foreign_key(op.f('stationssongs_ibfk_2'), 'stationssongs', 'stations', ['stationfk'], ['pk'])
    # op.create_foreign_key(op.f('stationssongs_ibfk_1'), 'stationssongs', 'songs', ['songfk'], ['pk'])
    # op.drop_constraint(None, 'stationsplaylists', type_='foreignkey')
    # op.drop_constraint(None, 'stationsplaylists', type_='foreignkey')
    # op.drop_constraint(None, 'stationsplaylists', type_='foreignkey')
    # op.create_foreign_key(op.f('stationsplaylists_ibfk_3'), 'stationsplaylists', 'users', ['lastmodifiedbyuserfk'], ['pk'])
    # op.create_foreign_key(op.f('stationsplaylists_ibfk_1'), 'stationsplaylists', 'playlists', ['playlistfk'], ['pk'])
    # op.create_foreign_key(op.f('stationsplaylists_ibfk_2'), 'stationsplaylists', 'stations', ['stationfk'], ['pk'])
    # op.drop_constraint(None, 'stationsalbums', type_='foreignkey')
    # op.drop_constraint(None, 'stationsalbums', type_='foreignkey')
    # op.drop_constraint(None, 'stationsalbums', type_='foreignkey')
    # op.create_foreign_key(op.f('stationsalbums_ibfk_3'), 'stationsalbums', 'users', ['lastmodifiedbyuserfk'], ['pk'])
    # op.create_foreign_key(op.f('stationsalbums_ibfk_1'), 'stationsalbums', 'albums', ['albumfk'], ['pk'])
    # op.create_foreign_key(op.f('stationsalbums_ibfk_2'), 'stationsalbums', 'stations', ['stationfk'], ['pk'])
    # op.drop_constraint(None, 'stationlogs', type_='foreignkey')
    # op.drop_constraint(None, 'stationlogs', type_='foreignkey')
    # op.drop_constraint(None, 'stationlogs', type_='foreignkey')
    # op.create_foreign_key(op.f('stationlogs_ibfk_2'), 'stationlogs', 'songs', ['songfk'], ['pk'])
    # op.create_foreign_key(op.f('stationlogs_ibfk_1'), 'stationlogs', 'stations', ['stationfk'], ['pk'])
    # op.create_foreign_key(op.f('stationlogs_ibfk_3'), 'stationlogs', 'users', ['userfk'], ['pk'])
    # op.drop_constraint(None, 'playlistssongs', type_='foreignkey')
    # op.drop_constraint(None, 'playlistssongs', type_='foreignkey')
    # op.drop_constraint(None, 'playlistssongs', type_='foreignkey')
    # op.create_foreign_key(op.f('playlistssongs_ibfk_1'), 'playlistssongs', 'songs', ['songfk'], ['pk'])
    # op.create_foreign_key(op.f('playlistssongs_ibfk_2'), 'playlistssongs', 'playlists', ['playlistfk'], ['pk'])
    # op.create_foreign_key(op.f('playlistssongs_ibfk_3'), 'playlistssongs', 'users', ['lastmodifiedbyuserfk'], ['pk'])
    # op.drop_constraint(None, 'lastplayed', type_='foreignkey')
    # op.drop_constraint(None, 'lastplayed', type_='foreignkey')
    # op.create_foreign_key(op.f('lastplayed_ibfk_1'), 'lastplayed', 'stations', ['stationfk'], ['pk'])
    # op.create_foreign_key(op.f('lastplayed_ibfk_2'), 'lastplayed', 'songs', ['songfk'], ['pk'])
    # ### end Alembic commands ###