"""combine_role_tables

Revision ID: b4113a98e44a
Revises: f0f6aa97edac
Create Date: 2026-02-01 23:28:08.957065

"""
from typing import Any, Sequence

from alembic import op, context
import sqlalchemy as sa
import musical_chairs_libs.dtos_and_utilities as mcr_u
from musical_chairs_libs.tables import userRoles

# revision identifiers, used by Alembic.
revision: str = 'b4113a98e44a'
down_revision: str | Sequence[str] | None = 'f702f8c0eeb2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = ['f702f8c0eeb2']


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not context.get_tag_argument():
        op.create_table('visitors',
            sa.Column('pk', sa.Integer(), nullable=False),
            sa.Column('ipv4address', sa.String(length=24), nullable=True),
            sa.Column('ipv6address', sa.String(length=50), nullable=True),
            sa.Column('useragenttxt', sa.Text(), nullable=False),
            sa.Column('hashua', sa.BINARY(length=16), nullable=False),
            sa.Column('lengthua', sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint('pk'),
            if_not_exists=True
        )
        op.create_index(
            'idx_visitor',
            'visitors',
            ['ipv6address', 'ipv4address', 'hashua', 'lengthua'],
            unique=False,
            if_not_exists=True
        )

        try:
            op.alter_column(
                'lastplayed',
                'timestamp',
                new_column_name='playedtimestamp',
                existing_type=sa.Double[float],
                existing_nullable=False,
                
            )
        except: pass

        try:
            op.alter_column(
                'playlists',
                'description',
                new_column_name='displayname',
                existing_type=sa.String(1000)
            )
        except: pass

        try:
            op.alter_column(
                'songs',
                'path', 
                new_column_name='treepath',
                existing_type=sa.String(2000),
                existing_nullable=False
            )
        except: pass

        try:
            op.alter_column(
                'songs',
                'disc', 
                new_column_name='discnum',
                existing_type=sa.Integer,
            )
        except: pass

        try:
            op.alter_column(
                'songs',
                'comment', 
                new_column_name='notes',
                existing_type=sa.String(2000)
            )
        except: pass

        try:
            op.alter_column(
                'songs',
                'hash', 
                new_column_name='filehash',
                existing_type=sa.BINARY(64)
            )
        except: pass

        try:
            op.alter_column(
                'songsartists',
                'comment', 
                new_column_name='notes',
                existing_type=sa.String(2000)
            )
        except: pass

        try:
            op.alter_column(
                'stationlogs',
                'timestamp',
                new_column_name='playedtimestamp',
                existing_type=sa.Double[float],
            )
        except: pass

        try:
            op.alter_column(
                'userroles',
                'count', 
                new_column_name='quota',
                existing_type=sa.Float[float],
                existing_nullable=False
            )
        except:pass

        op.add_column(
            'userroles',
            sa.Column('sphere', sa.String(length=50), nullable=False),
            if_not_exists=True
        )
        op.add_column(
            'userroles',
            sa.Column('keypath', sa.String(length=2000), nullable=True),
            if_not_exists=True
        )
        op.create_index(
            'idx_userroles2',
            'userroles',
            ['userfk', 'sphere', 'role'],
            if_not_exists=True
        )
        op.drop_constraint(
            'userroles_ibfk_1',
            table_name='userroles', 
            type_='foreignkey',
            if_exists=True
        )
        op.drop_index(
            op.f('idx_userroles'),
            table_name='userroles',
            if_exists=True
        )
        try:
            op.create_foreign_key(
                None,
                'userroles',
                'users',
                ['userfk'],
                ['pk'],
                ondelete='CASCADE',
            )
        except:
            pass

        op.execute(
            sa.update(userRoles)\
                .values(sphere = mcr_u.UserRoleSphere.Site.value)
        )
        
        try:
            stationPermissionsRows: list[dict[str, Any]] = [{
                'userfk': r['userfk'],
                'span': r['span'],
                'quota': r['count'],
                'priority': r['priority'],
                'sphere': mcr_u.UserRoleSphere.Station.value,
                'creationtimestamp': r["creationtimestamp"],
                'role': r['role'],
                'keypath': str(r['stationfk'])
            } for r in op.get_bind().execute(
                sa.text("SELECT * FROM stationuserpermissions"))\
                .mappings().fetchall()
            ]
            if stationPermissionsRows:
                op.bulk_insert(
                    userRoles,
                    stationPermissionsRows,
                )
        except:
            pass

        op.drop_table('stationuserpermissions', if_exists=True)

        op.drop_table('playlistuserpermissions', if_exists=True)

        op.drop_table('frienduserpermissions', if_exists=True)

        op.drop_table('pathuserpermissions', if_exists=True)

        op.drop_table('useragents', if_exists=True)


    for action in ["SELECT", "UPDATE", "INSERT", "DELETE"]:
        op.execute(
            f"GRANT {action} ON visitors TO "
            f"{mcr_u.DbUsers.API_USER("localhost")}"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###