"""user_tokens

Revision ID: 7d6c075f5607
Revises: 407c14b8feb1
Create Date: 2026-02-06 08:57:43.923512

"""
from typing import Sequence

from alembic import op
from nanoid import generate
from musical_chairs_libs.dtos_and_utilities.constants import (
    hidden_token_alphabet,
    public_token_alphabet
)
import sqlalchemy as sa
import musical_chairs_libs.tables as tbls


# revision identifiers, used by Alembic.
revision: str = '7d6c075f5607'
down_revision: str | Sequence[str] | None = '407c14b8feb1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('publictoken', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('hiddentoken', sa.String(length=50), nullable=False))

    userIds: list[int] = [r[0] for r in op.get_bind().execute(
        sa.text("SELECT pk FROM users")).fetchall()
    ]
    for id in userIds:
        stmt = sa.update(tbls.users).values(
            publictoken = generate(
                size=10,
                alphabet=public_token_alphabet
            ),
            hiddentoken = generate(
                size=16,
                alphabet=hidden_token_alphabet
            )
        )\
        .where(tbls.u_pk == id)
        op.execute(stmt)
    
    op.get_bind().commit()


    op.create_index('idx_publictoken', 'users', ['publictoken'], unique=True)
    op.create_index('idx_hiddentoken', 'users', ['hiddentoken'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hiddentoken', table_name='users')
    op.drop_index('idx_publictoken', table_name='users')
    op.drop_column('users', 'hiddentoken')
    op.drop_column('users', 'publictoken')
    # ### end Alembic commands ###