"""reorder_roles_sphere_index

Revision ID: 407c14b8feb1
Revises: b4113a98e44a
Create Date: 2026-02-04 16:50:32.488517

"""
from typing import Sequence

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '407c14b8feb1'
down_revision: str | Sequence[str] | None = 'b4113a98e44a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'idx_userroles_sphere',
        'userroles',
        ['sphere', 'userfk', 'role'],
        unique=False,
        if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_userroles_sphere', table_name='userroles')
    # ### end Alembic commands ###